### ISSUE TITLE
Bemerkungsfeld auch bei Terminzusage 

### ISSUE THREAD

**Issue by born73tanzen** [teamtasic/teamtasic-ionic#105]
auch bei einer Terminzusage Möglichkeit zu einer Bemerkungseingabe haben, dann in Anzeige 
mit einer grünen Sprechblase.

**Comment by JesseB0rn** [comment]
> auch bei einer Terminzusage Möglichkeit zu einer Bemerkungseingabe haben, dann in Anzeige 
> 
> mit einer grünen Sprechblase.
> 
> 
> 
> 

Ist schon
