### ISSUE TITLE
feat: Login mit Fingerprint

### ISSUE THREAD

**Issue by born73tanzen** [teamtasic/teamtasic-ionic#85]
User kann mit Smartphone Login mit Fingerprint aktivieren

**Comment by JesseB0rn** [comment]
Login mit Fingerprint bringt nichts, da die App im normalfall angemeldet bleibt. Passwordmanager mit Fingerprint funktioniert bereits

**Comment by born73tanzen** [comment]
bitte entsprechende Erklärung bei Hilfefunktion/Anleitung
